version: 2
jobs:
    test:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Linting
                command: npm run lint
            - run:
                name: Test run
                command: npm test
    publish:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/.npmrc
            - run:
                name: Configure git
                command: |
                    git config --global user.email "$GIT_USER_EMAIL"
                    git config --global user.name "$GIT_USER"
            - run:
                name: Patch package version
                command: npm version patch -m "Changed the package version to %s [skip ci]"
            - run:
                name: Push changes to the git repository
                command: git push -q https://${GITHUB_TOKEN}@github.com/SmartContractSecurity/SWC-registry-javascript.git master
            - run:
                name: Publish package to npm
                command: npm publish
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
            filters:
                branches:
                    only: master
            requires:
                - test
