version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - run:
            name: Install dependencies
            command:  cd swcregistry && npm install
        - run:
            name: Test run
            command: cd swcregistry && npm test