version: 2
jobs:
    test:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest'
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Test run
                command: npm test
    publish:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/.npmrc
            - run:
                name: Publish to npm
                command: npm version major && npm publish
            - run:
                name: Push changes
                command: |
                    git config --global user.email "$GIT_USER_EMAIL"
                    git config --global user.name "$GIT_USER"
                    git add . && git commit -am "Changed the package version [skip ci]" && git push -q https://${GITHUB_TOKEN}@github.com/SmartContractSecurity/SWC-registry-javascript.git master
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
            filters:
                branches:
                    only: master
            requires:
                - test
