version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
        - checkout
        - run:
            name: update-npm
            working_directory: swcregistry/
            command: 'sudo npm install -g npm@latest'
        - run:
            name: Test run
            working_directory: swcregistry/
            command: |  
              npm install
              npm run test